changelog:
  exclude:
    labels:
      - ignore-for-release
      - ci
      - duplicate
      - invalid
      - question
      - wontfix
      - help wanted
  categories:
    - title: Security
      labels:
        - area/security
        - dependencies/security
    - title: Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Deprecated
      labels:
        - deprecate
    - title: Removed
      labels:
        - remove
    - title: Dependencies
      labels:
        - dependencies
    - title: Others
      labels:
        - "*"
