apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: mcing-registry
port: 5151
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-mcing-dev
product: kind
kubernetesVersion: v1.28.15 # renovate: kindest/node
registry: mcing-registry
