apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcing-controller-manager
  namespace: mcing-system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: manager
        args:
        - --zap-log-level=5
        - --agent-image-name=mcing-agent:e2e
        env:
          - name: DEBUG_CONTROLLER
            value: "1"
