apiVersion: mcing.kmdkuk.com/v1alpha1
kind: Minecraft
metadata:
  name: minecraft-sample
spec:
  whitelist:
    enabled: true
    users:
    - kmdkuk
  ops:
    users:
    - kmdkuk
  podTemplate:
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java8
          env:
            - name: TYPE
              value: "SPIGOT"
            - name: VERSION
              value: "1.16.3"
            - name: EULA
              value: "true"
  serviceTemplate:
    spec:
      type: NodePort
  volumeClaimTemplates:
    - metadata:
        name: minecraft-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
  serverPropertiesConfigMapName: mcing-server-props
  otherConfigMapName: other-props
