apiVersion: mcing.kmdkuk.com/v1alpha1
kind: Minecraft
metadata:
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: minecraft-sample
    app.kubernetes.io/part-of: mcing
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mcing
  name: minecraft-sample
spec:
  # TODO(user): Add fields here
