apiVersion: mcing.kmdkuk.com/v1alpha1
kind: Minecraft
metadata:
  name: minecraft-sample
spec:
  podTemplate:
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java17
          env:
            - name: EULA
              value: "true"
  volumeClaimSpec:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: standard
    resources:
      requests:
        storage: 1Gi
