apiVersion: mcing.kmdkuk.com/v1alpha1
kind: Minecraft
metadata:
  name: minecraft-sample
spec:
  # whitelist:
  #   enabled: true
  #   users:
  #   - <invite player name>
  # ops:
  #   users:
  #   - <operator player name>
  podTemplate:
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java17
          env:
            - name: TYPE
              value: "PAPER"
            - name: VERSION
              value: "1.19.4"
            - name: EULA
              value: "true"
  serviceTemplate:
    spec:
      type: NodePort
  volumeClaimTemplates:
    - metadata:
        name: minecraft-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
  serverPropertiesConfigMapName: mcing-server-props
  otherConfigMapName: other-props
