// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/proto/agentrpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// ReloadRequest is the request message to execute `/reload` via rcon.
type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{0}
}

// *
// ReloadResponse is the response message of Reload
type ReloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadResponse) Reset() {
	*x = ReloadResponse{}
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadResponse) ProtoMessage() {}

func (x *ReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadResponse.ProtoReflect.Descriptor instead.
func (*ReloadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{1}
}

// *
// SyncWhitelistRequest is the request message to exec /whitelist via rcon
type SyncWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Users         []string               `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncWhitelistRequest) Reset() {
	*x = SyncWhitelistRequest{}
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWhitelistRequest) ProtoMessage() {}

func (x *SyncWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWhitelistRequest.ProtoReflect.Descriptor instead.
func (*SyncWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{2}
}

func (x *SyncWhitelistRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SyncWhitelistRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

// *
// SyncWhitelistResponse is the response message of SyncWhitelist
type SyncWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncWhitelistResponse) Reset() {
	*x = SyncWhitelistResponse{}
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWhitelistResponse) ProtoMessage() {}

func (x *SyncWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWhitelistResponse.ProtoReflect.Descriptor instead.
func (*SyncWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{3}
}

// *
// SyncWhitelistRequest is the request message to exec /whitelist via rcon
type SyncOpsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []string               `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOpsRequest) Reset() {
	*x = SyncOpsRequest{}
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOpsRequest) ProtoMessage() {}

func (x *SyncOpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOpsRequest.ProtoReflect.Descriptor instead.
func (*SyncOpsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{4}
}

func (x *SyncOpsRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

// *
// SyncOpsResponse is the response message of SyncOps
type SyncOpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOpsResponse) Reset() {
	*x = SyncOpsResponse{}
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOpsResponse) ProtoMessage() {}

func (x *SyncOpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOpsResponse.ProtoReflect.Descriptor instead.
func (*SyncOpsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{5}
}

type SaveOffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveOffRequest) Reset() {
	*x = SaveOffRequest{}
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOffRequest) ProtoMessage() {}

func (x *SaveOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOffRequest.ProtoReflect.Descriptor instead.
func (*SaveOffRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{6}
}

type SaveOffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveOffResponse) Reset() {
	*x = SaveOffResponse{}
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveOffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOffResponse) ProtoMessage() {}

func (x *SaveOffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOffResponse.ProtoReflect.Descriptor instead.
func (*SaveOffResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{7}
}

type SaveAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAllRequest) Reset() {
	*x = SaveAllRequest{}
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAllRequest) ProtoMessage() {}

func (x *SaveAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAllRequest.ProtoReflect.Descriptor instead.
func (*SaveAllRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{8}
}

type SaveAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAllResponse) Reset() {
	*x = SaveAllResponse{}
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAllResponse) ProtoMessage() {}

func (x *SaveAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAllResponse.ProtoReflect.Descriptor instead.
func (*SaveAllResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{9}
}

type SaveOnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveOnRequest) Reset() {
	*x = SaveOnRequest{}
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveOnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOnRequest) ProtoMessage() {}

func (x *SaveOnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOnRequest.ProtoReflect.Descriptor instead.
func (*SaveOnRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{10}
}

type SaveOnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveOnResponse) Reset() {
	*x = SaveOnResponse{}
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveOnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOnResponse) ProtoMessage() {}

func (x *SaveOnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOnResponse.ProtoReflect.Descriptor instead.
func (*SaveOnResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{11}
}

var File_pkg_proto_agentrpc_proto protoreflect.FileDescriptor

const file_pkg_proto_agentrpc_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/agentrpc.proto\x12\x05mcing\"\x0f\n" +
	"\rReloadRequest\"\x10\n" +
	"\x0eReloadResponse\"F\n" +
	"\x14SyncWhitelistRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x14\n" +
	"\x05users\x18\x02 \x03(\tR\x05users\"\x17\n" +
	"\x15SyncWhitelistResponse\"&\n" +
	"\x0eSyncOpsRequest\x12\x14\n" +
	"\x05users\x18\x01 \x03(\tR\x05users\"\x11\n" +
	"\x0fSyncOpsResponse\"\x10\n" +
	"\x0eSaveOffRequest\"\x11\n" +
	"\x0fSaveOffResponse\"\x10\n" +
	"\x0eSaveAllRequest\"\x11\n" +
	"\x0fSaveAllResponse\"\x0f\n" +
	"\rSaveOnRequest\"\x10\n" +
	"\x0eSaveOnResponse2\xef\x02\n" +
	"\x05Agent\x125\n" +
	"\x06Reload\x12\x14.mcing.ReloadRequest\x1a\x15.mcing.ReloadResponse\x12J\n" +
	"\rSyncWhitelist\x12\x1b.mcing.SyncWhitelistRequest\x1a\x1c.mcing.SyncWhitelistResponse\x128\n" +
	"\aSyncOps\x12\x15.mcing.SyncOpsRequest\x1a\x16.mcing.SyncOpsResponse\x128\n" +
	"\aSaveOff\x12\x15.mcing.SaveOffRequest\x1a\x16.mcing.SaveOffResponse\x128\n" +
	"\aSaveAll\x12\x15.mcing.SaveAllRequest\x1a\x16.mcing.SaveAllResponse\x125\n" +
	"\x06SaveOn\x12\x14.mcing.SaveOnRequest\x1a\x15.mcing.SaveOnResponseB#Z!github.com/kmdkuk/mcing/pkg/protob\x06proto3"

var (
	file_pkg_proto_agentrpc_proto_rawDescOnce sync.Once
	file_pkg_proto_agentrpc_proto_rawDescData []byte
)

func file_pkg_proto_agentrpc_proto_rawDescGZIP() []byte {
	file_pkg_proto_agentrpc_proto_rawDescOnce.Do(func() {
		file_pkg_proto_agentrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_agentrpc_proto_rawDesc), len(file_pkg_proto_agentrpc_proto_rawDesc)))
	})
	return file_pkg_proto_agentrpc_proto_rawDescData
}

var file_pkg_proto_agentrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_proto_agentrpc_proto_goTypes = []any{
	(*ReloadRequest)(nil),         // 0: mcing.ReloadRequest
	(*ReloadResponse)(nil),        // 1: mcing.ReloadResponse
	(*SyncWhitelistRequest)(nil),  // 2: mcing.SyncWhitelistRequest
	(*SyncWhitelistResponse)(nil), // 3: mcing.SyncWhitelistResponse
	(*SyncOpsRequest)(nil),        // 4: mcing.SyncOpsRequest
	(*SyncOpsResponse)(nil),       // 5: mcing.SyncOpsResponse
	(*SaveOffRequest)(nil),        // 6: mcing.SaveOffRequest
	(*SaveOffResponse)(nil),       // 7: mcing.SaveOffResponse
	(*SaveAllRequest)(nil),        // 8: mcing.SaveAllRequest
	(*SaveAllResponse)(nil),       // 9: mcing.SaveAllResponse
	(*SaveOnRequest)(nil),         // 10: mcing.SaveOnRequest
	(*SaveOnResponse)(nil),        // 11: mcing.SaveOnResponse
}
var file_pkg_proto_agentrpc_proto_depIdxs = []int32{
	0,  // 0: mcing.Agent.Reload:input_type -> mcing.ReloadRequest
	2,  // 1: mcing.Agent.SyncWhitelist:input_type -> mcing.SyncWhitelistRequest
	4,  // 2: mcing.Agent.SyncOps:input_type -> mcing.SyncOpsRequest
	6,  // 3: mcing.Agent.SaveOff:input_type -> mcing.SaveOffRequest
	8,  // 4: mcing.Agent.SaveAll:input_type -> mcing.SaveAllRequest
	10, // 5: mcing.Agent.SaveOn:input_type -> mcing.SaveOnRequest
	1,  // 6: mcing.Agent.Reload:output_type -> mcing.ReloadResponse
	3,  // 7: mcing.Agent.SyncWhitelist:output_type -> mcing.SyncWhitelistResponse
	5,  // 8: mcing.Agent.SyncOps:output_type -> mcing.SyncOpsResponse
	7,  // 9: mcing.Agent.SaveOff:output_type -> mcing.SaveOffResponse
	9,  // 10: mcing.Agent.SaveAll:output_type -> mcing.SaveAllResponse
	11, // 11: mcing.Agent.SaveOn:output_type -> mcing.SaveOnResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_agentrpc_proto_init() }
func file_pkg_proto_agentrpc_proto_init() {
	if File_pkg_proto_agentrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_agentrpc_proto_rawDesc), len(file_pkg_proto_agentrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_agentrpc_proto_goTypes,
		DependencyIndexes: file_pkg_proto_agentrpc_proto_depIdxs,
		MessageInfos:      file_pkg_proto_agentrpc_proto_msgTypes,
	}.Build()
	File_pkg_proto_agentrpc_proto = out.File
	file_pkg_proto_agentrpc_proto_goTypes = nil
	file_pkg_proto_agentrpc_proto_depIdxs = nil
}
