// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: pkg/proto/agentrpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// ReloadRequest is the request message to execute `/reload` via rcon.
type ReloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_agentrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{0}
}

// *
// ReloadResponse is the response message of Reload
type ReloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadResponse) Reset() {
	*x = ReloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_agentrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadResponse) ProtoMessage() {}

func (x *ReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadResponse.ProtoReflect.Descriptor instead.
func (*ReloadResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{1}
}

// *
// SyncWhitelistRequest is the request message to exec /whitelist via rcon
type SyncWhitelistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Users   []string `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *SyncWhitelistRequest) Reset() {
	*x = SyncWhitelistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_agentrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWhitelistRequest) ProtoMessage() {}

func (x *SyncWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWhitelistRequest.ProtoReflect.Descriptor instead.
func (*SyncWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{2}
}

func (x *SyncWhitelistRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SyncWhitelistRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

// *
// SyncWhitelistResponse is the response message of SyncWhitelist
type SyncWhitelistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncWhitelistResponse) Reset() {
	*x = SyncWhitelistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_agentrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWhitelistResponse) ProtoMessage() {}

func (x *SyncWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWhitelistResponse.ProtoReflect.Descriptor instead.
func (*SyncWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{3}
}

// *
// SyncWhitelistRequest is the request message to exec /whitelist via rcon
type SyncOpsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []string `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *SyncOpsRequest) Reset() {
	*x = SyncOpsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_agentrpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncOpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOpsRequest) ProtoMessage() {}

func (x *SyncOpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOpsRequest.ProtoReflect.Descriptor instead.
func (*SyncOpsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{4}
}

func (x *SyncOpsRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

// *
// SyncOpsResponse is the response message of SyncOps
type SyncOpsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncOpsResponse) Reset() {
	*x = SyncOpsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_agentrpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncOpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOpsResponse) ProtoMessage() {}

func (x *SyncOpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_agentrpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOpsResponse.ProtoReflect.Descriptor instead.
func (*SyncOpsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_agentrpc_proto_rawDescGZIP(), []int{5}
}

var File_pkg_proto_agentrpc_proto protoreflect.FileDescriptor

var file_pkg_proto_agentrpc_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x63, 0x69, 0x6e,
	0x67, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x46, 0x0a, 0x14, 0x53, 0x79, 0x6e, 0x63, 0x57, 0x68, 0x69, 0x74,
	0x65, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x17, 0x0a, 0x15,
	0x53, 0x79, 0x6e, 0x63, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a, 0x0e, 0x53, 0x79, 0x6e, 0x63, 0x4f, 0x70, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x11, 0x0a,
	0x0f, 0x53, 0x79, 0x6e, 0x63, 0x4f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0xc4, 0x01, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x35, 0x0a, 0x06, 0x52, 0x65,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x2e, 0x6d, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6d, 0x63, 0x69,
	0x6e, 0x67, 0x2e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x53, 0x79, 0x6e, 0x63, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x1b, 0x2e, 0x6d, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x57,
	0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x6d, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x57, 0x68, 0x69, 0x74,
	0x65, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x07, 0x53, 0x79, 0x6e, 0x63, 0x4f, 0x70, 0x73, 0x12, 0x15, 0x2e, 0x6d, 0x63, 0x69, 0x6e, 0x67,
	0x2e, 0x53, 0x79, 0x6e, 0x63, 0x4f, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x6d, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x4f, 0x70, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6d, 0x64, 0x6b, 0x75, 0x6b, 0x2f, 0x6d, 0x63, 0x69,
	0x6e, 0x67, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_agentrpc_proto_rawDescOnce sync.Once
	file_pkg_proto_agentrpc_proto_rawDescData = file_pkg_proto_agentrpc_proto_rawDesc
)

func file_pkg_proto_agentrpc_proto_rawDescGZIP() []byte {
	file_pkg_proto_agentrpc_proto_rawDescOnce.Do(func() {
		file_pkg_proto_agentrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_agentrpc_proto_rawDescData)
	})
	return file_pkg_proto_agentrpc_proto_rawDescData
}

var file_pkg_proto_agentrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_agentrpc_proto_goTypes = []interface{}{
	(*ReloadRequest)(nil),         // 0: mcing.ReloadRequest
	(*ReloadResponse)(nil),        // 1: mcing.ReloadResponse
	(*SyncWhitelistRequest)(nil),  // 2: mcing.SyncWhitelistRequest
	(*SyncWhitelistResponse)(nil), // 3: mcing.SyncWhitelistResponse
	(*SyncOpsRequest)(nil),        // 4: mcing.SyncOpsRequest
	(*SyncOpsResponse)(nil),       // 5: mcing.SyncOpsResponse
}
var file_pkg_proto_agentrpc_proto_depIdxs = []int32{
	0, // 0: mcing.Agent.Reload:input_type -> mcing.ReloadRequest
	2, // 1: mcing.Agent.SyncWhitelist:input_type -> mcing.SyncWhitelistRequest
	4, // 2: mcing.Agent.SyncOps:input_type -> mcing.SyncOpsRequest
	1, // 3: mcing.Agent.Reload:output_type -> mcing.ReloadResponse
	3, // 4: mcing.Agent.SyncWhitelist:output_type -> mcing.SyncWhitelistResponse
	5, // 5: mcing.Agent.SyncOps:output_type -> mcing.SyncOpsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_agentrpc_proto_init() }
func file_pkg_proto_agentrpc_proto_init() {
	if File_pkg_proto_agentrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_agentrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_agentrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_agentrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncWhitelistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_agentrpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncWhitelistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_agentrpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncOpsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_agentrpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncOpsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_agentrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_agentrpc_proto_goTypes,
		DependencyIndexes: file_pkg_proto_agentrpc_proto_depIdxs,
		MessageInfos:      file_pkg_proto_agentrpc_proto_msgTypes,
	}.Build()
	File_pkg_proto_agentrpc_proto = out.File
	file_pkg_proto_agentrpc_proto_rawDesc = nil
	file_pkg_proto_agentrpc_proto_goTypes = nil
	file_pkg_proto_agentrpc_proto_depIdxs = nil
}
